<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
        <MSBuildEnableWorkloadResolver>false</MSBuildEnableWorkloadResolver>
        <UsingMicrosoftNETSdkWorkloads>false</UsingMicrosoftNETSdkWorkloads>
        <SpaRoot>frontend\</SpaRoot>
        <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Atlassian.SDK" Version="13.0.0" />
      <PackageReference Include="Octokit" Version="14.0.0" />
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
      <PackageReference Include="Quartz.AspNetCore" Version="3.18.2" />
      <PackageReference Include="YamlDotNet" Version="17.1.0" />
      <PackageReference Include="Microsoft.Graph" Version="5.62.0" />
      <PackageReference Include="Azure.Identity" Version="1.13.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="wwwroot\assets\email.html" />
      <Content Update="frontend\**" CopyToOutputDirectory="Never" />
    </ItemGroup>

 


    <Target Name="DefineFrontendInputs">
        <ItemGroup>
            <FrontendInputs Include="$(SpaRoot)**\*" Exclude="$(SpaRoot)node_modules\**;$(SpaRoot)dist\**;$(SpaRoot)out\**" />
        </ItemGroup>
    </Target>

    <Target Name="BuildFrontend" BeforeTargets="Build" DependsOnTargets="DefineFrontendInputs" Inputs="@(FrontendInputs)" Outputs="$(SpaRoot)node_modules\.install-stamp;$(SpaRoot).build-stamp" Condition="'$(Configuration)' == 'Debug'">
        <Message Importance="high" Text="--- Building Frontend (Debug) ---" />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
        <Touch Files="$(SpaRoot)node_modules\.install-stamp" AlwaysCreate="true" />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
        <Touch Files="$(SpaRoot).build-stamp" AlwaysCreate="true" />
        <ItemGroup>
            <Content Include="wwwroot\**" Exclude="$(SpaRoot)**;$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        </ItemGroup>
    </Target>

    <Target Name="PublishFrontend" BeforeTargets="ComputeFilesToPublish" Condition="'$(Configuration)' == 'Release'">
        <Message Importance="high" Text="--- Building Frontend (Release) ---" />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
        <ItemGroup>
            <Content Include="wwwroot\**" Exclude="$(SpaRoot)**;$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <None Include="wwwroot\**" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
